### ISSUE TITLE
ImportError: No module named classification

### ISSUE THREAD

**Issue by andyyuan78** [jameshensman/pyGP#1]
export PYTHONPATH=~/github/src/pyGP/classification:$PYTHONPATH
export PYTHONPATH=~/github/src/pyGP:$PYTHONPATH

ubgpu@ubgpu:~/github/pyGP/src/testing$ python test_GP.py 
Traceback (most recent call last):
  File "test_GP.py", line 7, in <module>
    import pyGP
  File "../pyGP/**init**.py", line 4, in <module>
    from classification import *
ImportError: No module named classification
ubgpu@ubgpu:~/github/pyGP/src/testing$

**Comment by peteretelej** [comment]
Seems the classification folder (pyGP/classification) does not have a `__init__.py` file; it requires one in order to be treated as a package

**Comment by andyyuan78** [comment]
it works !
